### ISSUE TITLE
Option to disable automatic resourcepack download

### ISSUE THREAD

**Issue by DrkMatr1984** [benfah/CustomUtils#1]
I really like how you have this integrated, but I already use force-resourcepack to handle resourcepacks on my server and I can manually merge resource packs on my own. Could you make a config option and a boolean check in 
CustomUtils/src/main/java/me/benfah/cu/listener/PlayerJoinListener.java
that if the config option is false, don't send the resource pack to the player? Thanks!

**Comment by benfah** [comment]
Check the newest update (and commit if you want) 😄
